/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import LopTienIch.Auth;
import LopTienIch.ChuyenManHinhController;
import LopTienIch.DanhMucBean;
import LopTienIch.MsgBox;
import LopTienIch.XImage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

/**
 *
 * @author admin
 */
public class MHChinh extends javax.swing.JFrame {

    /**
     * Creates new form MHChinh2
     */
    public MHChinh() {
        initComponents();
        init();
        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
        controller.setView(jpnManHinhChinh, jlbManHinhChinh);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("ManHinhChinh", jpnManHinhChinh, jlbManHinhChinh));
        listItem.add(new DanhMucBean("QLHoaDon", jpnQLHoaDon, jlbQLHoaDon));
        listItem.add(new DanhMucBean("QLKhachHang", jpnQLKhachHang, jlbQLKhachHang));
        listItem.add(new DanhMucBean("QLMatHang", jpnQLMatHang, jlbQLMatHang));
        listItem.add(new DanhMucBean("QLDichVu", jpnQLDichVu, jlbQLDichVu));
        listItem.add(new DanhMucBean("QLNhanVien", jpQLNhanVien, jlbQLNhanVien));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        Destop = new javax.swing.JDesktopPane();
        jpnMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnManHinhChinh = new javax.swing.JPanel();
        jlbManHinhChinh = new javax.swing.JLabel();
        jpnQLHoaDon = new javax.swing.JPanel();
        jlbQLHoaDon = new javax.swing.JLabel();
        jpnQLKhachHang = new javax.swing.JPanel();
        jlbQLKhachHang = new javax.swing.JLabel();
        jpnQLMatHang = new javax.swing.JPanel();
        jlbQLMatHang = new javax.swing.JLabel();
        jpnQLDichVu = new javax.swing.JPanel();
        jlbQLDichVu = new javax.swing.JLabel();
        jpQLNhanVien = new javax.swing.JPanel();
        jlbQLNhanVien = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        mniKetThuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniMatHang = new javax.swing.JMenuItem();
        mniHoaDon = new javax.swing.JMenuItem();
        mniDichVu = new javax.swing.JMenuItem();
        mniKhachHang = new javax.swing.JMenuItem();
        mniNhanVien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniLuongKhachHang = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniGioiThieu = new javax.swing.JMenuItem();
        mniHuongDan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(232, 64, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/LogoGiat_50px.png"))); // NOI18N
        jLabel1.setText("CỬA HÀNG GIẶT ỦI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jpnManHinhChinh.setBackground(new java.awt.Color(0, 153, 0));

        jlbManHinhChinh.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbManHinhChinh.setForeground(new java.awt.Color(255, 255, 255));
        jlbManHinhChinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MHChinh_80px.png"))); // NOI18N
        jlbManHinhChinh.setText("Màn hình chính");

        javax.swing.GroupLayout jpnManHinhChinhLayout = new javax.swing.GroupLayout(jpnManHinhChinh);
        jpnManHinhChinh.setLayout(jpnManHinhChinhLayout);
        jpnManHinhChinhLayout.setHorizontalGroup(
            jpnManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnManHinhChinhLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbManHinhChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnManHinhChinhLayout.setVerticalGroup(
            jpnManHinhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnManHinhChinhLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbManHinhChinh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQLHoaDon.setBackground(new java.awt.Color(0, 153, 0));

        jlbQLHoaDon.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbQLHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MHHoaDon_80px.png"))); // NOI18N
        jlbQLHoaDon.setText("Quản lý hóa đơn");

        javax.swing.GroupLayout jpnQLHoaDonLayout = new javax.swing.GroupLayout(jpnQLHoaDon);
        jpnQLHoaDon.setLayout(jpnQLHoaDonLayout);
        jpnQLHoaDonLayout.setHorizontalGroup(
            jpnQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLHoaDonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbQLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQLHoaDonLayout.setVerticalGroup(
            jpnQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLHoaDonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbQLHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQLKhachHang.setBackground(new java.awt.Color(0, 153, 0));

        jlbQLKhachHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbQLKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MHKhachHang_80px.png"))); // NOI18N
        jlbQLKhachHang.setText("Quản lý khách hàng");

        javax.swing.GroupLayout jpnQLKhachHangLayout = new javax.swing.GroupLayout(jpnQLKhachHang);
        jpnQLKhachHang.setLayout(jpnQLKhachHangLayout);
        jpnQLKhachHangLayout.setHorizontalGroup(
            jpnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLKhachHangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQLKhachHangLayout.setVerticalGroup(
            jpnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLKhachHangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbQLKhachHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQLMatHang.setBackground(new java.awt.Color(0, 153, 0));

        jlbQLMatHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbQLMatHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLMatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MHMatHang_80px.png"))); // NOI18N
        jlbQLMatHang.setText("Quản lý mặt hàng");

        javax.swing.GroupLayout jpnQLMatHangLayout = new javax.swing.GroupLayout(jpnQLMatHang);
        jpnQLMatHang.setLayout(jpnQLMatHangLayout);
        jpnQLMatHangLayout.setHorizontalGroup(
            jpnQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLMatHangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbQLMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQLMatHangLayout.setVerticalGroup(
            jpnQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLMatHangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbQLMatHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQLDichVu.setBackground(new java.awt.Color(0, 153, 0));

        jlbQLDichVu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbQLDichVu.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MHDichVu_80px.png"))); // NOI18N
        jlbQLDichVu.setText("Quản lý dịch vụ");

        javax.swing.GroupLayout jpnQLDichVuLayout = new javax.swing.GroupLayout(jpnQLDichVu);
        jpnQLDichVu.setLayout(jpnQLDichVuLayout);
        jpnQLDichVuLayout.setHorizontalGroup(
            jpnQLDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLDichVuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlbQLDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQLDichVuLayout.setVerticalGroup(
            jpnQLDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLDichVuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbQLDichVu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpQLNhanVien.setBackground(new java.awt.Color(0, 153, 0));

        jlbQLNhanVien.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbQLNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MHNhanVien_80px.png"))); // NOI18N
        jlbQLNhanVien.setText("Quản lý nhân viên");

        javax.swing.GroupLayout jpQLNhanVienLayout = new javax.swing.GroupLayout(jpQLNhanVien);
        jpQLNhanVien.setLayout(jpQLNhanVienLayout);
        jpQLNhanVienLayout.setHorizontalGroup(
            jpQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLNhanVienLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlbQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpQLNhanVienLayout.setVerticalGroup(
            jpQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLNhanVienLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbQLNhanVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnQLDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnQLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnQLMatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnManHinhChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnManHinhChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnQLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnQLMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnQLDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        lblTrangThai.setBackground(new java.awt.Color(255, 204, 51));
        lblTrangThai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(255, 153, 51));
        lblTrangThai.setText("Hệ thống quản lý cửa hàng giặt ủi !");

        lblDongHo.setBackground(new java.awt.Color(51, 51, 0));
        lblDongHo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 0, 0));
        lblDongHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDongHo.setText("Time");

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Destop.setLayer(jpnMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Destop.setLayer(lblTrangThai, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Destop.setLayer(lblDongHo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Destop.setLayer(jpnView, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DestopLayout = new javax.swing.GroupLayout(Destop);
        Destop.setLayout(DestopLayout);
        DestopLayout.setHorizontalGroup(
            DestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DestopLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DestopLayout.createSequentialGroup()
                        .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                        .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        DestopLayout.setVerticalGroup(
            DestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DestopLayout.createSequentialGroup()
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Destop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Destop)
        );

        jMenuBar1.setMinimumSize(new java.awt.Dimension(66, 35));

        jMenu1.setBackground(new java.awt.Color(51, 255, 204));
        jMenu1.setText("Danh mục");
        jMenu1.setAutoscrolls(true);

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mniDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_enter_30px.png"))); // NOI18N
        mniDangNhap.setText("Đăng nhập");
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangNhap);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dangxuat.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangXuat);

        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/doimatkhau.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(mniDoiMatKhau);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_cancel_30px.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        jMenu1.add(mniKetThuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");
        jMenu2.setAutoscrolls(true);

        mniMatHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        mniMatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/giohang.png"))); // NOI18N
        mniMatHang.setText("Mặt hàng");
        mniMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMatHangActionPerformed(evt);
            }
        });
        jMenu2.add(mniMatHang);

        mniHoaDon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        mniHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hoadon.png"))); // NOI18N
        mniHoaDon.setText("Hóa đơn");
        mniHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHoaDonActionPerformed(evt);
            }
        });
        jMenu2.add(mniHoaDon);

        mniDichVu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        mniDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dichvu.png"))); // NOI18N
        mniDichVu.setText("Dịch vụ");
        mniDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDichVuActionPerformed(evt);
            }
        });
        jMenu2.add(mniDichVu);

        mniKhachHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mniKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khachhang.png"))); // NOI18N
        mniKhachHang.setText("Khách hàng");
        mniKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhachHangActionPerformed(evt);
            }
        });
        jMenu2.add(mniKhachHang);

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/suanv.png"))); // NOI18N
        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(mniNhanVien);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Báo cáo");
        jMenu3.setAutoscrolls(true);

        mniLuongKhachHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_MASK));
        mniLuongKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/baocaodichvu.png"))); // NOI18N
        mniLuongKhachHang.setText("Biểu đồ");
        mniLuongKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLuongKhachHangActionPerformed(evt);
            }
        });
        jMenu3.add(mniLuongKhachHang);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Hệ thống");
        jMenu4.setAutoscrolls(true);

        mniGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gioithieu.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        jMenu4.add(mniGioiThieu);

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mniHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/huongdansd.png"))); // NOI18N
        mniHuongDan.setText("Hướng dẫn");
        mniHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongDanActionPerformed(evt);
            }
        });
        jMenu4.add(mniHuongDan);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        openDangNhap();
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed

        ketThuc();
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMatHangActionPerformed
        openQuanLyMatHang();
    }//GEN-LAST:event_mniMatHangActionPerformed

    private void mniHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHoaDonActionPerformed
        openQLHoaDon();
    }//GEN-LAST:event_mniHoaDonActionPerformed

    private void mniDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDichVuActionPerformed

        openDichVu();
    }//GEN-LAST:event_mniDichVuActionPerformed

    private void mniKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhachHangActionPerformed
        openKhachHang();
    }//GEN-LAST:event_mniKhachHangActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        openNhanVien();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniLuongKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLuongKhachHangActionPerformed
        openLuongKhachHang();
    }//GEN-LAST:event_mniLuongKhachHangActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed

    }//GEN-LAST:event_mniGioiThieuActionPerformed

    private void mniHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongDanActionPerformed

    }//GEN-LAST:event_mniHuongDanActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MHChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MHChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MHChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MHChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MHChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Destop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbManHinhChinh;
    private javax.swing.JLabel jlbQLDichVu;
    private javax.swing.JLabel jlbQLHoaDon;
    private javax.swing.JLabel jlbQLKhachHang;
    private javax.swing.JLabel jlbQLMatHang;
    private javax.swing.JLabel jlbQLNhanVien;
    private javax.swing.JPanel jpQLNhanVien;
    private javax.swing.JPanel jpnManHinhChinh;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnQLDichVu;
    private javax.swing.JPanel jpnQLHoaDon;
    private javax.swing.JPanel jpnQLKhachHang;
    private javax.swing.JPanel jpnQLMatHang;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDichVu;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHoaDon;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniKhachHang;
    private javax.swing.JMenuItem mniLuongKhachHang;
    private javax.swing.JMenuItem mniMatHang;
    private javax.swing.JMenuItem mniNhanVien;
    // End of variables declaration//GEN-END:variables

    void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());

        new CuaSoChao(this, true).setVisible(true);
        new DangNhap(this, true).setVisible(true);

        new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);
                lblDongHo.setText(text);
            }
        }).start();
    }

    void openDangNhap() {
        new DangNhap(this, true).setVisible(true);        
    }

    void dangXuat() {
        Auth.clear();//xóa use hiện tại        
        new DangNhap(this, true).setVisible(true);//và hiển thị cửa sổ đăng nhập trở lại để đăng nhập mới
    }

    void openDoiMatKhau() {
        if (Auth.isLogin()) {//kiểm tra xem đăng nhập hay chưa
            for (JInternalFrame frmChild : Destop.getAllFrames()) {
                frmChild.dispose();
            }
            DoiMatKhau cd = new DoiMatKhau();
            cd.setTitle("Đổi mật khẩu");
            cd.setLocation(this.getWidth() / 2 - cd.getWidth() / 2, (this.getHeight() - 50) / 2 - cd.getHeight() / 2 - 100);
            Destop.add(cd);
            cd.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");//còn chưa thì thông báo vui lòng đăng nhập
        }
    }

    void ketThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc?")) {
            System.exit(0);
        }
    }

    private void openNhanVien() {
        for (JInternalFrame frmChild : Destop.getAllFrames()) {
            frmChild.doDefaultCloseAction();
        }
        QLNhanVien cd = new QLNhanVien();
        cd.setTitle("Quản lý nhân viên");
        cd.setLocation(this.getWidth() / 2 - cd.getWidth() / 2, (this.getHeight() - 10) / 2 - cd.getHeight() / 2 - 80);
        Destop.add(cd);
        cd.setVisible(true);
    }

    private void openDichVu() {
        for (JInternalFrame frmChild : Destop.getAllFrames()) {
            frmChild.dispose();
        }
        QLDichVu cd = new QLDichVu();
        cd.setTitle("Quản lý dịch vụ");
        cd.setLocation(this.getWidth() / 2 - cd.getWidth() / 2, (this.getHeight() - 10) / 2 - cd.getHeight() / 2 - 80);
        Destop.add(cd);
        cd.setVisible(true);
    }

    private void openKhachHang() {
        for (JInternalFrame frmChild : Destop.getAllFrames()) {
            frmChild.dispose();
        }
        QLKhachhang cd = new QLKhachhang();
        cd.setTitle("Quản lý khach hang");
        cd.setLocation(this.getWidth() / 2 - cd.getWidth() / 2, (this.getHeight() - 10) / 2 - cd.getHeight() / 2 - 80);
        Destop.add(cd);
        cd.setVisible(true);
    }

    private void openQuanLyMatHang() {
        for (JInternalFrame frmChild : Destop.getAllFrames()) {
            frmChild.dispose();
        }
        QLMatHang cd = new QLMatHang();
        cd.setTitle("Quản lý mặt hàng");
        cd.setLocation(this.getWidth() / 2 - cd.getWidth() / 2, (this.getHeight() - 10) / 2 - cd.getHeight() / 2 - 90);
        Destop.add(cd);
        cd.setVisible(true);
    }

    private void openLuongKhachHang() {
        for (JInternalFrame frmChild : Destop.getAllFrames()) {
            frmChild.dispose();
        }
        ThongKe cd = new ThongKe();
        cd.setTitle("Luong khách hàng");
        cd.setLocation(this.getWidth() / 2 - cd.getWidth() / 2, (this.getHeight() - 10) / 2 - cd.getHeight() / 2 - 90);
        Destop.add(cd);
        cd.setVisible(true);
    }

    private void openQLHoaDon() {
        for (JInternalFrame frmChild : Destop.getAllFrames()) {
            frmChild.dispose();
        }
        QLHoaDon cd = new QLHoaDon();
        cd.setTitle("Quản lý hóa đơn");
        cd.setLocation(this.getWidth() / 2 - cd.getWidth() / 2, (this.getHeight() - 10) / 2 - cd.getHeight() / 2 - 90);
        Destop.add(cd);
        cd.setVisible(true);
    }
}
