/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LopTienIch;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author admin
 */
public class ManHinhChinhJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManHinhChinhJPanel
     */
    public ManHinhChinhJPanel() {
        initComponents();
        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
        controller.setView2(jpnQLHoaDon, jlbQLHoaDon);
        
        List<DanhMucBean> listItem = new ArrayList<>();        
        listItem.add(new DanhMucBean("QLHoaDon", jpnQLHoaDon, jlbQLHoaDon));
        listItem.add(new DanhMucBean("QLKhachHang", jpnQLKhachHang, jlbQLKhachHang));
        listItem.add(new DanhMucBean("QLMatHang", jpnQLMatHang, jlbQLMatHang));
        listItem.add(new DanhMucBean("QLDichVu", jpnQLDichVu, jlbQLDichVu));
        listItem.add(new DanhMucBean("QLNhanVien", jpQLNhanVien, jlbQLNhanVien));
        
        controller.setEvent2(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jpnMenu = new javax.swing.JPanel();
        jpnQLHoaDon = new javax.swing.JPanel();
        jlbQLHoaDon = new javax.swing.JLabel();
        jpnQLKhachHang = new javax.swing.JPanel();
        jlbQLKhachHang = new javax.swing.JLabel();
        jpnQLMatHang = new javax.swing.JPanel();
        jlbQLMatHang = new javax.swing.JLabel();
        jpnQLDichVu = new javax.swing.JPanel();
        jlbQLDichVu = new javax.swing.JLabel();
        jpQLNhanVien = new javax.swing.JPanel();
        jlbQLNhanVien = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        jpnMenu.setBackground(new java.awt.Color(153, 153, 153));

        jpnQLHoaDon.setBackground(new java.awt.Color(255, 51, 51));

        jlbQLHoaDon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbQLHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbQLHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BangHoaDon_70px.png"))); // NOI18N

        javax.swing.GroupLayout jpnQLHoaDonLayout = new javax.swing.GroupLayout(jpnQLHoaDon);
        jpnQLHoaDon.setLayout(jpnQLHoaDonLayout);
        jpnQLHoaDonLayout.setHorizontalGroup(
            jpnQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLHoaDonLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jlbQLHoaDon)
                .addGap(20, 20, 20))
        );
        jpnQLHoaDonLayout.setVerticalGroup(
            jpnQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbQLHoaDon)
                .addGap(20, 20, 20))
        );

        jpnQLKhachHang.setBackground(new java.awt.Color(255, 51, 51));
        jpnQLKhachHang.setPreferredSize(new java.awt.Dimension(129, 124));

        jlbQLKhachHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbQLKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbQLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BangKhachHang_70pxx.png"))); // NOI18N

        javax.swing.GroupLayout jpnQLKhachHangLayout = new javax.swing.GroupLayout(jpnQLKhachHang);
        jpnQLKhachHang.setLayout(jpnQLKhachHangLayout);
        jpnQLKhachHangLayout.setHorizontalGroup(
            jpnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLKhachHangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbQLKhachHang)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpnQLKhachHangLayout.setVerticalGroup(
            jpnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLKhachHangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbQLKhachHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQLMatHang.setBackground(new java.awt.Color(255, 51, 51));
        jpnQLMatHang.setPreferredSize(new java.awt.Dimension(129, 124));

        jlbQLMatHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbQLMatHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLMatHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbQLMatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BangMathang_70px.png"))); // NOI18N

        javax.swing.GroupLayout jpnQLMatHangLayout = new javax.swing.GroupLayout(jpnQLMatHang);
        jpnQLMatHang.setLayout(jpnQLMatHangLayout);
        jpnQLMatHangLayout.setHorizontalGroup(
            jpnQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLMatHangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbQLMatHang)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpnQLMatHangLayout.setVerticalGroup(
            jpnQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLMatHangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbQLMatHang)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jpnQLDichVu.setBackground(new java.awt.Color(255, 51, 51));
        jpnQLDichVu.setPreferredSize(new java.awt.Dimension(129, 124));

        jlbQLDichVu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbQLDichVu.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbQLDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BangDichVu_70px.png"))); // NOI18N

        javax.swing.GroupLayout jpnQLDichVuLayout = new javax.swing.GroupLayout(jpnQLDichVu);
        jpnQLDichVu.setLayout(jpnQLDichVuLayout);
        jpnQLDichVuLayout.setHorizontalGroup(
            jpnQLDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLDichVuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbQLDichVu)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jpnQLDichVuLayout.setVerticalGroup(
            jpnQLDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLDichVuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlbQLDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpQLNhanVien.setBackground(new java.awt.Color(255, 51, 51));
        jpQLNhanVien.setPreferredSize(new java.awt.Dimension(129, 124));

        jlbQLNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbQLNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BangNhanVien_70px.png"))); // NOI18N

        javax.swing.GroupLayout jpQLNhanVienLayout = new javax.swing.GroupLayout(jpQLNhanVien);
        jpQLNhanVien.setLayout(jpQLNhanVienLayout);
        jpQLNhanVienLayout.setHorizontalGroup(
            jpQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpQLNhanVienLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jlbQLNhanVien)
                .addGap(24, 24, 24))
        );
        jpQLNhanVienLayout.setVerticalGroup(
            jpQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQLNhanVienLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlbQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jpnQLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jpnQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jpnQLMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jpnQLDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jpQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnQLMatHang, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jpnQLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jpnQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnQLDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jpQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jpnMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jpnView, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jlbQLDichVu;
    private javax.swing.JLabel jlbQLHoaDon;
    private javax.swing.JLabel jlbQLKhachHang;
    private javax.swing.JLabel jlbQLMatHang;
    private javax.swing.JLabel jlbQLNhanVien;
    private javax.swing.JPanel jpQLNhanVien;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnQLDichVu;
    private javax.swing.JPanel jpnQLHoaDon;
    private javax.swing.JPanel jpnQLKhachHang;
    private javax.swing.JPanel jpnQLMatHang;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
